### ISSUE TITLE
Instantiation pattern seems backwards

### ISSUE THREAD

**Issue by cthoyt** [INCATools/ontology-access-kit#126]
I'm not a big fan of this pattern:

```python
resource = OntologyResource(slug='go-nucleus.obo', directory='input', local=True)
oi = ProntoImplementation(resource)
```

It makes it seem like the implementation is based off of the resource itself, and not that the implementation is a "backend". I'd rather see code that looks like this:

```python
oi = get_interface(slug='go-nucleus.obo', directory='input', local=True, implementation="pronto")
# OR
oi = get_interface(slug='go-nucleus.obo', directory='input', local=True, implementation=ProntoImplementation)
```

In fact, we've written so many "backend"-like interfaces in [PyKEEN](https://github.com/pykeen/pykeen/) that we spun out the utilities we were using for that into a separate package [`class_resolver`](https://github.com/cthoyt/class-resolver) to support these kinds things (e.g., lookup of a class based on a string or class). Will send a PR to demonstrate

**Comment by cthoyt** [comment]
After looking at what's going on in the OntologyResource class, I'm now further wondering where this information persists, and have a slightly different looking idea in mind.

**Comment by cmungall** [comment]
The separation is intentional - see also the convenience functions here:

https://incatools.github.io/ontology-access-kit/selectors.html#functions

I think it would be easy to expand this to allow the constructor args from an OntologyResource to be passed in instead of a full object

There are definitely some things that might be good to refactor. I don't love having `directory` be a property of the OntologyResource object. But we want something that abstracts over (1) a path to `fbbt.obo` (2) the logical resource `fbbt.obo` that can be accessed from the OBO Library by pronto. But maybe simply allowing URLs here is easiest.

It may be best to start with requirements for the system

- files, URLs, or query endpoints, or services
- local files or files from a repository
- extensible for simple versioning support
- for files, a variety of formats that may be extended in future
- sensible default implementations given a logical description of a resource (e.g. "I want to use this obo file -> use pronto/fastobo to parse it")
- ability to be explicit about implementations (e.g. "I want to use this OWL file AND I want to use sqlite NOT rdflib")
- plugin architecture (https://incatools.github.io/ontology-access-kit/howtos/write-a-plugin.html)
- symmetric abilities for saving/dumping ontologies
