### ISSUE TITLE
Add an adapter for Translator SRI NodeNormalizer endpoint

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-access-kit#397]
Wrap the NodeNormalizer to return SSSOM objects

https://nodenormalization-sri.renci.org/docs#/

Suggested mapping:

 - if mapping involves conflation, use closeMatch
 - if mapping does not involve conflation, use exactMatch
 - use ManualMappingCuration for justification

cc @matentzn @gaurav @sierra-moxon

**Comment by gaurav** [comment]
That makes sense! You could figure out exactly which IDs were conflated in and which ones weren't by running queries with conflation turned on and off. I've opened an issue to add this functionality directly to NodeNorm: https://github.com/TranslatorSRI/NodeNormalization/issues/158

We've previously discussed what NodeNorm results would look like in SSSOM (https://github.com/TranslatorSRI/NodeNormalization/issues/111) and plan to modify Babel so that it can generate compendia in SSSOM format (https://github.com/TranslatorSRI/Babel/issues/33). We currently do this conversion by hand using the Babel Validator (https://github.com/TranslatorSRI/babel-validation/pull/6), but that isn't very well documented as yet.

**Comment by sierra-moxon** [comment]
Wish I could put more than one rocket ship on this -- I saw the PR too -- this is a great idea!
