### ISSUE TITLE
cell ontology cl.obo error

### ISSUE THREAD

**Issue by noamiz5060** [INCATools/ontology-access-kit#441]
Hello hello
I'm using the package mostly for finding ancestors and descendants 
I've tried to load the cl-obo file but every time I try to use it, it returns errors to me (for example 
![image](https://user-images.githubusercontent.com/111743864/216079649-1e7292ff-699e-402d-a71f-456812182232.png)

The error I get here is 'NCBITaxon:9606'
I also get other errors with other functions, like curie 
I've tried different ways the upload the obo file, thinking that's the problem.
`(slug='cl-basic.obo', local=True)`
`(slug='cl-basic.obo', local=False)`
`(slug='http://purl.obolibrary.org/obo/cl/cl-basic.obo', local=False)`

I'd love any type of help

p.s  Another important question. Is it possible to get a cell descendants WITHOUT develop_from relationship? The reason I'm using this package is because in others, they treat develop_from as 'is_a' or 'subclass_of' and it ruins what I try to build. I'd love to hear how to do it

an example, Bm3 delta doesn't have any descendants, but Bm3 has a develop_from connection with it.
![image](https://user-images.githubusercontent.com/111743864/216079881-fdc486c2-8748-45d6-90d9-6b460888941b.png)

**Comment by cmungall** [comment]
Hi there, the issue here is that by default the obo adapter uses pronto, and the pronto is quite strict and considers things in the obo file to be bugs. https://github.com/althonos/pronto/issues/159 these should actually be fixed with cl but there is less incentive to do this as other parsers just ignore these problems.

If you are using the release version of cl you may want to use the sqlite backend. Just swap `cl.obo` for `sqlite:obo:cl`. See https://incatools.github.io/ontology-access-kit/intro/tutorial07.html

And yes, OAK is explicitly designed not to hardwire the assumptions a lot of other libraries make, you have complete control. The screenshot you show has you passing in a list of vocabulary variablea `[IS_A, PART_OF]`, and so only these will be used for ancestry)

See https://incatools.github.io/ontology-access-kit/intro/tutorial01.html#introduction-to-graphs-and-trees

https://github.com/INCATools/ontology-access-kit/blob/main/notebooks/Neuro/CL-Neuro-Tutorial.ipynb

(these focus on the command line, but they illustrate the general principle)

**Comment by noamiz5060** [comment]
> Hi there, the issue here is that by default the obo adapter uses pronto, and the pronto is quite strict and considers things in the obo file to be bugs. [althonos/pronto#159](https://github.com/althonos/pronto/issues/159) these should actually be fixed with cl but there is less incentive to do this as other parsers just ignore these problems.
> 
> If you are using the release version of cl you may want to use the sqlite backend. Just swap `cl.obo` for `sqlite:obo:cl`. See https://incatools.github.io/ontology-access-kit/intro/tutorial07.html
> 
> And yes, OAK is explicitly designed not to hardwire the assumptions a lot of other libraries make, you have complete control. The screenshot you show has you passing in a list of vocabulary variablea `[IS_A, PART_OF]`, and so only these will be used for ancestry)
> 
> See https://incatools.github.io/ontology-access-kit/intro/tutorial01.html#introduction-to-graphs-and-trees
> 
> https://github.com/INCATools/ontology-access-kit/blob/main/notebooks/Neuro/CL-Neuro-Tutorial.ipynb
> 
> (these focus on the command line, but they illustrate the general principle)

you're a life saver
cheers mate
