### ISSUE TITLE
Add SOP for handling pywin32 github actions failing

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-access-kit#554]
Sometimes we get spurious fails with the windows github action. We definitely want to keep this going as we want to ensure everything works on windows.

Previously @dalito kindly provided a fix to the poetry.lock, but unfortunately I can't find that commit, and it's not clear what the SOP should be, given this file is generated automatically.

@hrshdhgd you mentioned this works:

`poetry update --only click`

but why exactly does this work and where should we run this in our cycle?

**Comment by dalito** [comment]
Previously the poetry.lock file was missing a hash for the pywin-binaries for one specific Python version (Python 3.10).

I don't know how to get there but it seems that the failing poetry.lock files were generated with poetry 1.4.0 and the working ones with 1.4.2 (or 1.3.x). The fix was kind of automatically done when you merged a PR with a correct lock file.

**Comment by hrshdhgd** [comment]
You saw this again in #552 because the [PR clearly shows deleting the above dependency code block](https://github.com/INCATools/ontology-access-kit/pull/553/files#diff-f53a023eedfa3fbf2925ec7dc76eecdc954ea94b7e47065393dbad519613dc89L4297-L4298) from the `poetry.lock` file.


So the fix (so to speak) is:
- use the latest version of poetry (>=v1.4.2)
- run `poetry update` on your system and a new user will never see the problem. 

https://github.com/INCATools/ontology-access-kit/pull/555 resolves this once and for all. If other PRs are seeing the same problem, they need to double check the `poetry` version and merge down the main branch after this PR is merged.

**Comment by cmungall** [comment]
This *seems* to have just worked itself out...?
