### ISSUE TITLE
Feature request - expose the version of ontologies that are downloaded

### ISSUE THREAD

**Issue by justaddcoffee** [INCATools/ontology-access-kit#604]
It'd be useful to know which version of a given ontology is retrieved by OAK

For example, we are going to run something similar to this:

`runoak -i semsimian:sqlite:obo:phenio similarity -p i,p i^HP: @ i^MP: --min-jaccard-similarity 0.5`

to generate an all by all table of similarities and make this available as an artifact for Monarch users. This retrieves the sqlite version of phenio obviously. We'd like to also tell them what version of PHENIO was used for this 

I think we could probably get this sqlite dump manually and figure out the version from this, but maybe it would be useful for OAK to provide this feature at some point?

per convo with @hrshdhgd @caufieldjh

**Comment by caufieldjh** [comment]
Even just the `LastModified` value for an object in an S3 bucket would be useful, as that can be compared to something else (in this case, the semsql version vs. the latest KG-Phenio build)

**Comment by matentzn** [comment]
Big yes! There must be a comment for retrieving ontology annotations?

**Comment by hrshdhgd** [comment]
So basically get the metadata from [here](https://s3.amazonaws.com/bbop-sqlite/) at the time of download. Once downloaded and present in the cache (via `pystow`, there must be a way to determine the value of the `<LastModified>` tag corresponding to that `*.db` file. 

Questions:
- Is this assumption correct?
- Would it make sense to have this data in the db file itself so the information is contained within one resource?
- If so, I wonder if this is a task for [`semsql`](https://github.com/INCATools/semantic-sql) that creates the db file.

**Comment by caufieldjh** [comment]
Absolutely correct - something like this can retrieve the metadata: https://github.com/Knowledge-Graph-Hub/kg-obo/blob/c7356efc6f262ae83dfedfca2a918a12058c564f/kg_obo/stats.py#L113-L149

**Comment by hrshdhgd** [comment]
But this will always show the latest version since it is getting it from the bucket. How does one compare it to the cached `db` file?

**Comment by matentzn** [comment]
I am missing something. Can you verify that there is no such thing as:

```
runoak -i X ontology-annotations
```

? I know that specific command does not exist, but maybe it exists in a different form. The Ontology object has all the versioning information, title, description, contributors and more that are potentially interesting for users..

**Comment by caufieldjh** [comment]
There are the commands `ontology-metadata` and `ontology-versions` - the former calls `ontology_metadata_map` in the BasicOntologyInterface, but that just raises a NotImplementedError. The latter only works for Bioportal ontology versions. 

There's the `statistics` command, too - that may actually get closest since it traverses metadata properties.

But even if that command exists, it should be run any time a new ontology is downloaded so the user knows about any version changes.

**Comment by cmungall** [comment]
Don’t hardcode assumptions about s3. Why not just get the versioniri
triple? See existing commands

**Comment by hrshdhgd** [comment]
Thanks Chris! Dug into the code and found an existing command that tells us exactly what we need
```
runoak -i sqlite:obo:phenio ontology-metadata --all
```

gives me 
```
id:
- obo:phenio.owl
dcterms:description:
- None
dcterms:license:
- <https://creativecommons.org/licenses/unspecified>
dcterms:title:
- Phenomics Integrated Ontology
owl:versionIRI:
- obo:phenio/releases/2022-10-13/phenio.owl
owl:versionInfo:
- '2022-10-13'
rdf:type:
- owl:Ontology
sh:prefix:
- obo
schema:url:
- http://purl.obolibrary.org/obo/phenio.owl
rdfs:isDefinedBy:
- http://purl.obolibrary.org/obo/obo.owl
```

**Comment by caufieldjh** [comment]
That works (and I think the versionIRI should be included in the output even w/o a verbose flag) for most cases, the exceptions being OBOs like [ARO](https://dashboard.obofoundry.org/dashboard/aro/dashboard.html) of [CIDO](https://dashboard.obofoundry.org/dashboard/cido/dashboard.html) where there's inconsistency in IRI and/or version formatting. Perhaps that isn't an issue since it isn't OAK's purpose to normalize versions, but if the purpose is to let users know they are working with a db of a given ontology that aligns with a known version, then versionIRI will only do so much

**Comment by cmungall** [comment]
@caufieldjh agreed. There are always ontologies that don't conform to standards, but in this case adherence is pretty good, and the non conformers are likely useless from a semsim POV

so the remaining issue is how to report. I think we should follow SSSOM TSV patterns here

**Comment by cmungall** [comment]
closing as completed - reopen if additional functionality required
